//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class SistemaFinancieroEntities : DbContext
    {
        public SistemaFinancieroEntities()
            : base("name=SistemaFinancieroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arqueo> Arqueo { get; set; }
        public DbSet<ArqueoDetalle> ArqueoDetalle { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Correlativo> Correlativo { get; set; }
        public DbSet<DiasFestivos> DiasFestivos { get; set; }
        public DbSet<Fiador> Fiador { get; set; }
        public DbSet<Garantia> Garantia { get; set; }
        public DbSet<Negocio> Negocio { get; set; }
        public DbSet<Pago> Pago { get; set; }
        public DbSet<PlanPago> PlanPago { get; set; }
        public DbSet<Prestamo> Prestamo { get; set; }
        public DbSet<RegistroSistema> RegistroSistema { get; set; }
        public DbSet<Seguridad_Aplicacion> Seguridad_Aplicacion { get; set; }
        public DbSet<Seguridad_PermisoAplicacion> Seguridad_PermisoAplicacion { get; set; }
        public DbSet<Seguridad_Rol> Seguridad_Rol { get; set; }
        public DbSet<Seguridad_Usuario> Seguridad_Usuario { get; set; }
        public DbSet<Seguridad_Usuario_Rol> Seguridad_Usuario_Rol { get; set; }
        public DbSet<Tarifario> Tarifario { get; set; }
        public DbSet<TasaBanco> TasaBanco { get; set; }
        public DbSet<Trabajador> Trabajador { get; set; }
        public DbSet<BloqueoOperativo> BloqueoOperativo { get; set; }
        public DbSet<VisitaNoPago> VisitaNoPago { get; set; }
        public DbSet<Oficina> Oficina { get; set; }
        public DbSet<TipoNegocio> TipoNegocio { get; set; }
    }
}
