//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidades;
    
    public partial class SistemaFacturacionEntities : DbContext
    {
        public SistemaFacturacionEntities()
            : base("name=SistemaFacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<ScheduleType> ScheduleType { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tmaasignaturas> tmaasignaturas { get; set; }
        public virtual DbSet<tmaasignaturascat> tmaasignaturascat { get; set; }
        public virtual DbSet<tmaasignaturasdet> tmaasignaturasdet { get; set; }
        public virtual DbSet<tmaasignaturasdetfinal> tmaasignaturasdetfinal { get; set; }
        public virtual DbSet<tmaasignaturasdetsemestral> tmaasignaturasdetsemestral { get; set; }
        public virtual DbSet<tmaasignaturasdocente> tmaasignaturasdocente { get; set; }
        public virtual DbSet<tmaasignaturasfuentes> tmaasignaturasfuentes { get; set; }
        public virtual DbSet<tmaasignaturasfuentesdet> tmaasignaturasfuentesdet { get; set; }
        public virtual DbSet<tmaasignaturaspadrehijo> tmaasignaturaspadrehijo { get; set; }
        public virtual DbSet<tmaasignaturasporcentual> tmaasignaturasporcentual { get; set; }
        public virtual DbSet<tmaasignaturasterminal> tmaasignaturasterminal { get; set; }
        public virtual DbSet<tmabecas> tmabecas { get; set; }
        public virtual DbSet<tmabecasconcepto> tmabecasconcepto { get; set; }
        public virtual DbSet<tmabecasdet> tmabecasdet { get; set; }
        public virtual DbSet<tmabecasinfoen> tmabecasinfoen { get; set; }
        public virtual DbSet<tmacalificaciones> tmacalificaciones { get; set; }
        public virtual DbSet<tmacertificados> tmacertificados { get; set; }
        public virtual DbSet<tmadocentes> tmadocentes { get; set; }
        public virtual DbSet<tmaestudiante> tmaestudiante { get; set; }
        public virtual DbSet<tmaestudianteh> tmaestudianteh { get; set; }
        public virtual DbSet<tmafrecuencias> tmafrecuencias { get; set; }
        public virtual DbSet<tmahorarios> tmahorarios { get; set; }
        public virtual DbSet<tmahorariosdocente> tmahorariosdocente { get; set; }
        public virtual DbSet<tmalistas> tmalistas { get; set; }
        public virtual DbSet<tmalistastmp> tmalistastmp { get; set; }
        public virtual DbSet<tmaparciales> tmaparciales { get; set; }
        public virtual DbSet<tmapensum> tmapensum { get; set; }
        public virtual DbSet<tmapensumdet> tmapensumdet { get; set; }
        public virtual DbSet<tmapensumdias> tmapensumdias { get; set; }
        public virtual DbSet<tmapensumperiodo> tmapensumperiodo { get; set; }
        public virtual DbSet<tmapromocion> tmapromocion { get; set; }
        public virtual DbSet<tmareconsanc> tmareconsanc { get; set; }
        public virtual DbSet<tmareconsancdet> tmareconsancdet { get; set; }
        public virtual DbSet<tmasemestre> tmasemestre { get; set; }
        public virtual DbSet<tmatutor> tmatutor { get; set; }
        public virtual DbSet<tmebodega> tmebodega { get; set; }
        public virtual DbSet<tmecajas> tmecajas { get; set; }
        public virtual DbSet<tmecategorias> tmecategorias { get; set; }
        public virtual DbSet<tmeconceptos> tmeconceptos { get; set; }
        public virtual DbSet<tmefacturas> tmefacturas { get; set; }
        public virtual DbSet<tmefacturasdet> tmefacturasdet { get; set; }
        public virtual DbSet<tmefamilia> tmefamilia { get; set; }
        public virtual DbSet<tmeinfobancos> tmeinfobancos { get; set; }
        public virtual DbSet<tmeinventario> tmeinventario { get; set; }
        public virtual DbSet<tmeinventarioges> tmeinventarioges { get; set; }
        public virtual DbSet<tmeinventariogesdet> tmeinventariogesdet { get; set; }
        public virtual DbSet<tmetransacciones> tmetransacciones { get; set; }
        public virtual DbSet<tmxautorizaciones> tmxautorizaciones { get; set; }
        public virtual DbSet<tmxautorizacionesdet> tmxautorizacionesdet { get; set; }
        public virtual DbSet<tmxcargos> tmxcargos { get; set; }
        public virtual DbSet<tmxcierre> tmxcierre { get; set; }
        public virtual DbSet<tmxconfiguracion> tmxconfiguracion { get; set; }
        public virtual DbSet<tmxcontador> tmxcontador { get; set; }
        public virtual DbSet<tmxemailconf> tmxemailconf { get; set; }
        public virtual DbSet<tmxempresa> tmxempresa { get; set; }
        public virtual DbSet<tmxlog> tmxlog { get; set; }
        public virtual DbSet<tmxlogsesion> tmxlogsesion { get; set; }
        public virtual DbSet<tmxniveles> tmxniveles { get; set; }
        public virtual DbSet<tmxpais> tmxpais { get; set; }
        public virtual DbSet<tmxusuarios> tmxusuarios { get; set; }
        public virtual DbSet<UserSector> UserSector { get; set; }
        public virtual DbSet<tmareparaciones> tmareparaciones { get; set; }
        public virtual DbSet<tmxlogerror> tmxlogerror { get; set; }
    }
}
