//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueo
    {
        public long IdArqueo { get; set; }
        public string IdAnalista { get; set; }
        public System.DateTime FechaArqueo { get; set; }
        public decimal MontoSistema { get; set; }
        public decimal MontoEntregado { get; set; }
        public decimal Diferencia { get; set; }
        public string Observacion { get; set; }
        public byte Estado { get; set; }
        public Nullable<decimal> TasaBanco { get; set; }
        public decimal MontoMinuta { get; set; }
        public decimal MontoAutoFondeo { get; set; }
    }
}
