//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiador
    {
        public string CedulaFiador { get; set; }
        public string NombreFiador { get; set; }
        public string DireccionFiador { get; set; }
        public string EstadoCivilFiador { get; set; }
        public string SexoFiador { get; set; }
        public string Telefono1Fiador { get; set; }
        public string Telefono2Fiador { get; set; }
        public string CorreoFiador { get; set; }
        public string IdCliente { get; set; }
        public byte EstadoFiador { get; set; }
    }
}
