//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public long IdGarantia { get; set; }
        public string NumeroPrestamo { get; set; }
        public string NombreGarantia { get; set; }
        public string DescripcionGarantia { get; set; }
        public string Modelo { get; set; }
    }
}
