//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public long IdNegocio { get; set; }
        public string NombreNegocio { get; set; }
        public string DireccionNegocio { get; set; }
        public string Telefono1 { get; set; }
        public string TipoNegocio { get; set; }
        public string Descripcion { get; set; }
        public byte[] Foto1 { get; set; }
        public byte[] Foto2 { get; set; }
        public byte[] Foto3 { get; set; }
        public Nullable<byte> Estado { get; set; }
        public string IdCliente { get; set; }
    }
}
