//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public long IdPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string NumeroPrestamo { get; set; }
        public decimal MontoPago { get; set; }
        public string IdTrabajador { get; set; }
        public byte Estado { get; set; }
    }
}
