//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPago
    {
        public long IdPlanPago { get; set; }
        public int NumeroCuota { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string NumeroPrestamo { get; set; }
        public decimal Cuota { get; set; }
        public decimal Credito { get; set; }
        public byte Estado { get; set; }
        public Nullable<System.DateTime> FechaCuotaPagada { get; set; }
        public Nullable<int> DiasEnMora { get; set; }
    }
}
