//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public long IdPrestamo { get; set; }
        public string NumeroPrestamo { get; set; }
        public string IdCliente { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaDesembolso { get; set; }
        public int Plazo { get; set; }
        public int Frecuencia { get; set; }
        public Nullable<decimal> MontoPrestamo { get; set; }
        public Nullable<decimal> TasaInteres { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public Nullable<decimal> TotalPrestamo { get; set; }
        public Nullable<decimal> Intereses { get; set; }
        public byte EstadoPrestamo { get; set; }
        public string IdTrabajador { get; set; }
        public string Observacion { get; set; }
        public decimal Seguro { get; set; }
        public string IdFiador { get; set; }
        public Nullable<int> IdNegocio { get; set; }
        public Nullable<int> PlazoMeses { get; set; }
        public string AnalistaAnterior { get; set; }
        public string FechaTraslado { get; set; }
        public string FechaAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public Nullable<byte> TipoPrestamo { get; set; }
        public string UsuarioSolicitud { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public byte[] FotoDesembolso { get; set; }
        public int IdOficina { get; set; }
    }
}
