//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> DayId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Hour { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Event Event { get; set; }
        public virtual ScheduleType ScheduleType { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
