//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifario
    {
        public int IdTarifario { get; set; }
        public int MontoInicial { get; set; }
        public int MontoFinal { get; set; }
        public decimal Tasa { get; set; }
        public int Plazo { get; set; }
        public int Frecuencia { get; set; }
        public int Cuota { get; set; }
        public byte Estado { get; set; }
    }
}
