//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaasignaturasdetsemestral
    {
        public long id_codigo { get; set; }
        public Nullable<int> annio { get; set; }
        public Nullable<int> semestre { get; set; }
        public string grado { get; set; }
        public string seccion { get; set; }
        public string id_estudiante { get; set; }
        public Nullable<int> id_asignatura { get; set; }
        public Nullable<int> nota { get; set; }
        public Nullable<int> espadre { get; set; }
        public string tipocalculo { get; set; }
        public Nullable<int> numero_lista { get; set; }
    
        public virtual tmaasignaturas tmaasignaturas { get; set; }
    }
}
