//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaasignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmaasignaturas()
        {
            this.tmaasignaturasdet = new HashSet<tmaasignaturasdet>();
            this.tmaasignaturasdetfinal = new HashSet<tmaasignaturasdetfinal>();
            this.tmaasignaturasdetsemestral = new HashSet<tmaasignaturasdetsemestral>();
            this.tmaasignaturasdocente = new HashSet<tmaasignaturasdocente>();
            this.tmaasignaturaspadrehijo = new HashSet<tmaasignaturaspadrehijo>();
            this.tmaasignaturasporcentual = new HashSet<tmaasignaturasporcentual>();
            this.tmaasignaturasterminal = new HashSet<tmaasignaturasterminal>();
            this.tmapensumdet = new HashSet<tmapensumdet>();
        }
    
        public int id_asignatura { get; set; }
        public string nombre_oficial { get; set; }
        public string alias { get; set; }
        public Nullable<int> id_frecuencia { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_califica { get; set; }
        public Nullable<int> annio { get; set; }
        public Nullable<int> id_fuente { get; set; }
        public Nullable<int> id_cat { get; set; }
        public string nombre_corto { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual tmaasignaturascat tmaasignaturascat { get; set; }
        public virtual tmaasignaturasfuentes tmaasignaturasfuentes { get; set; }
        public virtual tmacalificaciones tmacalificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdet> tmaasignaturasdet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdetfinal> tmaasignaturasdetfinal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdetsemestral> tmaasignaturasdetsemestral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdocente> tmaasignaturasdocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturaspadrehijo> tmaasignaturaspadrehijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasporcentual> tmaasignaturasporcentual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasterminal> tmaasignaturasterminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmapensumdet> tmapensumdet { get; set; }
    }
}
