//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaasignaturaspadrehijo
    {
        public long id_codigo { get; set; }
        public Nullable<int> id_asignatura_p { get; set; }
        public string nombre_oficial_p { get; set; }
        public Nullable<int> id_asignatura_h { get; set; }
        public string nombre_oficial_h { get; set; }
        public Nullable<int> id_pensum { get; set; }
    
        public virtual tmaasignaturas tmaasignaturas { get; set; }
        public virtual tmapensum tmapensum { get; set; }
    }
}
