//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmabecasinfoen
    {
        public long idtrans { get; set; }
        public Nullable<int> annio { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<int> parcial { get; set; }
        public string codest { get; set; }
        public string becaid { get; set; }
        public Nullable<bool> EN { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<int> CO { get; set; }
        public Nullable<int> PR { get; set; }
        public Nullable<int> PRF { get; set; }
    
        public virtual tmaestudiante tmaestudiante { get; set; }
    }
}
