//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmabecasdet
    {
        public long codigo { get; set; }
        public string id_estudiante { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> grado { get; set; }
        public string seccion { get; set; }
        public Nullable<int> id_beca { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string estado { get; set; }
        public string autoriza { get; set; }
        public Nullable<int> annio { get; set; }
        public string activa { get; set; }
        public Nullable<int> MontoBeca { get; set; }
        public Nullable<int> CuotaMensual { get; set; }
        public string Observacion { get; set; }
    
        public virtual tmabecas tmabecas { get; set; }
    }
}
