//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmabecasconcepto
    {
        public long id { get; set; }
        public Nullable<int> id_beca { get; set; }
        public string id_concepto { get; set; }
        public Nullable<int> PorcentajeDescuento { get; set; }
        public Nullable<int> PorcentajeCobro { get; set; }
    
        public virtual tmabecas tmabecas { get; set; }
        public virtual tmeconceptos tmeconceptos { get; set; }
    }
}
