//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmadocentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmadocentes()
        {
            this.tmaasignaturasdet = new HashSet<tmaasignaturasdet>();
            this.tmaasignaturasdocente = new HashSet<tmaasignaturasdocente>();
            this.tmahorariosdocente = new HashSet<tmahorariosdocente>();
            this.tmareconsancdet = new HashSet<tmareconsancdet>();
        }
    
        public int id_docente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string sexo { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string pais { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_celular { get; set; }
        public string email { get; set; }
        public string estadocivil { get; set; }
        public string titulo { get; set; }
        public string estudiosavanzados { get; set; }
        public string tiposangre { get; set; }
        public string impedimentos { get; set; }
        public string religion { get; set; }
        public string info_emergencia { get; set; }
        public string fecha_ingreso { get; set; }
        public string fecha_salida { get; set; }
        public string tipo_identificacion { get; set; }
        public string numero_identificacion { get; set; }
        public string nacionalidad { get; set; }
        public Nullable<int> id_hijo { get; set; }
        public string cargo { get; set; }
        public string estado { get; set; }
        public string motivo_retiro { get; set; }
        public string guia_grado { get; set; }
        public string guia_seccion { get; set; }
        public string nro_seguro { get; set; }
        public string guarda_usuario { get; set; }
        public string Correo_Institucional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdet> tmaasignaturasdet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturasdocente> tmaasignaturasdocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmahorariosdocente> tmahorariosdocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmareconsancdet> tmareconsancdet { get; set; }
    }
}
