//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmaestudianteh
    {
        public long idtabla { get; set; }
        public string id_estudiante { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> annio_lectivo { get; set; }
        public string becado { get; set; }
        public Nullable<int> numero_lista { get; set; }
        public Nullable<int> id_beca { get; set; }
        public Nullable<int> id_docente { get; set; }
        public Nullable<int> id_horario { get; set; }
        public string cod_familiar { get; set; }
        public string fecha_nacimiento { get; set; }
        public string tipo_sangre { get; set; }
        public string nivel { get; set; }
        public string seccion { get; set; }
        public string motivo_retiro { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string celular1 { get; set; }
        public string celular2 { get; set; }
        public Nullable<int> nro_hermanos { get; set; }
        public string religion { get; set; }
        public string primeracomunion { get; set; }
        public string bautizado { get; set; }
        public string direccion { get; set; }
        public string departamento { get; set; }
        public string municipio { get; set; }
        public string confirmacion { get; set; }
        public string vivecon { get; set; }
        public string estadocivilpadres { get; set; }
        public string representante { get; set; }
        public string guarda_usuario { get; set; }
        public Nullable<System.DateTime> fecha_reingreso { get; set; }
        public string calculo { get; set; }
        public string promocion { get; set; }
    }
}
