//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmahorarios
    {
        public long id { get; set; }
        public string periodo { get; set; }
        public string lunes { get; set; }
        public string martes { get; set; }
        public string miercoles { get; set; }
        public string jueves { get; set; }
        public string viernes { get; set; }
        public string sabado { get; set; }
        public string domingo { get; set; }
        public Nullable<int> grado { get; set; }
        public string seccion { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<int> parcial { get; set; }
        public Nullable<int> annio { get; set; }
        public Nullable<int> id_pensum { get; set; }
    
        public virtual tmapensum tmapensum { get; set; }
    }
}
