//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmapensum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmapensum()
        {
            this.tmaasignaturaspadrehijo = new HashSet<tmaasignaturaspadrehijo>();
            this.tmahorarios = new HashSet<tmahorarios>();
            this.tmapensumdet = new HashSet<tmapensumdet>();
        }
    
        public int id_pensum { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<int> parcial { get; set; }
        public string grado { get; set; }
        public string seccion { get; set; }
        public Nullable<int> annio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmaasignaturaspadrehijo> tmaasignaturaspadrehijo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmahorarios> tmahorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmapensumdet> tmapensumdet { get; set; }
    }
}
