//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmapromocion
    {
        public long id_codigo { get; set; }
        public string id_estudiante { get; set; }
        public Nullable<int> annio { get; set; }
        public string grado { get; set; }
        public string seccion { get; set; }
        public Nullable<int> aprobados { get; set; }
        public Nullable<int> reprobados_mined { get; set; }
        public Nullable<int> reprobados_ipls { get; set; }
        public string situacion { get; set; }
        public Nullable<int> tolerancia_mined { get; set; }
        public Nullable<int> tolerancia_ipls { get; set; }
    
        public virtual tmaestudiante tmaestudiante { get; set; }
    }
}
