//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmareconsancdet
    {
        public int id_codigo { get; set; }
        public Nullable<int> id_docente { get; set; }
        public string id_estudiante { get; set; }
        public Nullable<int> id_reconsanc { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
    
        public virtual tmadocentes tmadocentes { get; set; }
        public virtual tmaestudiante tmaestudiante { get; set; }
        public virtual tmareconsanc tmareconsanc { get; set; }
    }
}
