//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmasemestre
    {
        public int id_semestre { get; set; }
        public Nullable<int> annio { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> id_parcial { get; set; }
    }
}
