//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmatutor
    {
        public long id_codigo { get; set; }
        public string id_tutor { get; set; }
        public string tutela { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string profesion { get; set; }
        public string tipo_identificacion { get; set; }
        public string numero_identificacion { get; set; }
        public string nacionalidad { get; set; }
        public string lazofamiliar { get; set; }
        public string id_estudiante { get; set; }
        public string telefono_casa { get; set; }
        public string telefono_trabajo { get; set; }
        public string telefono_movil { get; set; }
        public string direccion_casa { get; set; }
        public string direccion_trabajo { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public string cod_familiar { get; set; }
        public string email { get; set; }
        public string estado_civil { get; set; }
        public string religion { get; set; }
        public string motivo_retiro { get; set; }
        public Nullable<int> orden { get; set; }
        public string estado { get; set; }
        public string email2 { get; set; }
    
        public virtual tmaestudiante tmaestudiante { get; set; }
    }
}
