//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmecajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmecajas()
        {
            this.tmefacturas = new HashSet<tmefacturas>();
        }
    
        public string id_caja { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string estado { get; set; }
        public Nullable<double> tipocambio { get; set; }
        public string mensaje1 { get; set; }
        public string mensaje2 { get; set; }
    
        public virtual tmxusuarios tmxusuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmefacturas> tmefacturas { get; set; }
    }
}
