//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmeconceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmeconceptos()
        {
            this.tmabecasconcepto = new HashSet<tmabecasconcepto>();
        }
    
        public string id_concepto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<double> recargo { get; set; }
        public string frecuencia { get; set; }
        public string estado { get; set; }
        public string aplica { get; set; }
        public string perfil { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public Nullable<int> orden_mes { get; set; }
        public string id_categoria { get; set; }
        public string id_concepto_mora { get; set; }
        public Nullable<int> orden_concepto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmabecasconcepto> tmabecasconcepto { get; set; }
        public virtual tmecategorias tmecategorias { get; set; }
    }
}
