//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmefacturasdet
    {
        public long id { get; set; }
        public string id_factura { get; set; }
        public string id_item { get; set; }
        public string nombre_item { get; set; }
        public string tipo_item { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> preciounitario { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual tmefacturas tmefacturas { get; set; }
    }
}
