//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmefacturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmefacturas()
        {
            this.tmefacturasdet = new HashSet<tmefacturasdet>();
        }
    
        public string id_factura { get; set; }
        public string tipo_factura { get; set; }
        public string id_caja { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> tipo_cambio { get; set; }
        public string id_estudiante { get; set; }
        public string anombrede { get; set; }
        public Nullable<double> total_cordobas { get; set; }
        public Nullable<double> total_dolares { get; set; }
        public Nullable<double> cliente_paga { get; set; }
        public Nullable<double> cliente_cambio { get; set; }
        public Nullable<System.DateTime> fecha_cancela { get; set; }
        public string estado { get; set; }
        public string estado_por { get; set; }
        public string forma_pago { get; set; }
        public string detalles { get; set; }
    
        public virtual tmaestudiante tmaestudiante { get; set; }
        public virtual tmecajas tmecajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmefacturasdet> tmefacturasdet { get; set; }
    }
}
