//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmeinventariogesdet
    {
        public long id_codigo { get; set; }
        public Nullable<long> id_gestion { get; set; }
        public string id_inventario { get; set; }
        public string prod_nombre { get; set; }
        public string tipo_operacion { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual tmeinventario tmeinventario { get; set; }
        public virtual tmeinventarioges tmeinventarioges { get; set; }
    }
}
