//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmeinfobancos
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NoRef { get; set; }
        public string CodAlum { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public string Numero { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<bool> Duplicado { get; set; }
        public string Notas { get; set; }
        public string TipoBanco { get; set; }
        public int IdBanco { get; set; }
    }
}
