//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmeinventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tmeinventario()
        {
            this.tmeinventariogesdet = new HashSet<tmeinventariogesdet>();
        }
    
        public string id_inventario { get; set; }
        public string prod_nombre { get; set; }
        public string prod_descripcion { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<int> stockminimo { get; set; }
        public Nullable<int> stockactual { get; set; }
        public string id_bodega { get; set; }
        public string estado { get; set; }
        public string enventa { get; set; }
    
        public virtual tmebodega tmebodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmeinventariogesdet> tmeinventariogesdet { get; set; }
    }
}
