//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmetransacciones
    {
        public long idtrans { get; set; }
        public string id_estudiante { get; set; }
        public Nullable<int> orden { get; set; }
        public string id_concepto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> total_cordobas { get; set; }
        public Nullable<double> total_dolar { get; set; }
        public string estado { get; set; }
        public string estadopor { get; set; }
        public Nullable<System.DateTime> fecha_vencimiento { get; set; }
        public string id_factura_banco { get; set; }
        public Nullable<int> annio_lectivo { get; set; }
        public string id_categoria { get; set; }
        public Nullable<System.DateTime> Fecha_Carga { get; set; }
        public string Observacion { get; set; }
    
        public virtual tmecategorias tmecategorias { get; set; }
    }
}
