//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxautorizacionesdet
    {
        public long id_codigo { get; set; }
        public Nullable<int> id_autorizacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario_solicita { get; set; }
        public string usuario_aprueba { get; set; }
        public string respuesta { get; set; }
    
        public virtual tmxautorizaciones tmxautorizaciones { get; set; }
    }
}
