//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxconfiguracion
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> annio { get; set; }
        public string fecha_desde { get; set; }
        public string fecha_hasta { get; set; }
        public Nullable<int> semestre { get; set; }
        public Nullable<int> parcial { get; set; }
        public string firma1 { get; set; }
        public string cargo1 { get; set; }
        public string firma2 { get; set; }
        public string cargo2 { get; set; }
        public string firma3 { get; set; }
        public string cargo3 { get; set; }
        public string estado { get; set; }
    }
}
