//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxempresa
    {
        public int id_empresa { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono_conv { get; set; }
        public string telefax { get; set; }
        public string telefono_cel { get; set; }
        public string email { get; set; }
        public string apartado_postal { get; set; }
        public string apoderado_legal { get; set; }
        public string siglas { get; set; }
        public byte[] logotipo { get; set; }
        public string sitioweb { get; set; }
        public string lema { get; set; }
        public string nroruc { get; set; }
    }
}
