//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxemailconf
    {
        public int id { get; set; }
        public string id_descripcion { get; set; }
        public string correo_origen { get; set; }
        public string correo_origen_nombre { get; set; }
        public string correo_origen_clave { get; set; }
        public Nullable<int> smtpserver_port { get; set; }
        public string smtpserver_host { get; set; }
        public string correo_replyto { get; set; }
        public string piecorreo_html { get; set; }
    }
}
