//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxlog
    {
        public long id_codigo { get; set; }
        public string usuario { get; set; }
        public string pantalla { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string pcname { get; set; }
        public string pcip { get; set; }
        public string pcuser { get; set; }
        public string pcos { get; set; }
        public string versiga { get; set; }
    }
}
