//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmxniveles
    {
        public int id_codigo { get; set; }
        public string grado { get; set; }
        public string seccion { get; set; }
        public string nivel { get; set; }
        public string jornada { get; set; }
        public string estado { get; set; }
        public string ubicacion { get; set; }
    }
}
