//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        public string CedulaTrabajador { get; set; }
        public string NombreTrabajador { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string EstadoCivil { get; set; }
        public string Sexo { get; set; }
        public byte Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string PersonaEmergencia { get; set; }
        public string TelefonoEmergencia { get; set; }
        public int IdOficina { get; set; }
    }
}
