//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitaNoPago
    {
        public long IdVisita { get; set; }
        public string NumeroPrestamo { get; set; }
        public string IdTrabajador { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public int Estado { get; set; }
    }
}
